spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/trips
    username: test_user
    password: qwerty
    driverClassName: org.postgresql.Driver